// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/providers/user_item/user_item_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/models/grouped_user_item.dart' as _i6;
import 'package:frontend/models/user_item.dart' as _i5;
import 'package:frontend/services/user_item/user_item_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserItemService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserItemService extends _i1.Mock implements _i2.UserItemService {
  MockUserItemService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<List<_i5.UserItem>> getUserItems() =>
      (super.noSuchMethod(
            Invocation.method(#getUserItems, []),
            returnValue: _i4.Future<List<_i5.UserItem>>.value(<_i5.UserItem>[]),
          )
          as _i4.Future<List<_i5.UserItem>>);

  @override
  List<_i6.GroupedUserItem> groupUserItems(List<_i5.UserItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#groupUserItems, [items]),
            returnValue: <_i6.GroupedUserItem>[],
          )
          as List<_i6.GroupedUserItem>);

  @override
  _i4.Future<void> saveUserItemBatch(List<_i5.UserItem>? items) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserItemBatch, [items]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserItem, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
