// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widgets/user_item/user_item_detail_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:frontend/models/auth/register_response.dart' as _i5;
import 'package:frontend/providers/auth/auth_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i2.AuthStatus.idle,
          )
          as _i2.AuthStatus);

  @override
  bool get isLeftHanded =>
      (super.noSuchMethod(Invocation.getter(#isLeftHanded), returnValue: false)
          as bool);

  @override
  bool get highContrast =>
      (super.noSuchMethod(Invocation.getter(#highContrast), returnValue: false)
          as bool);

  @override
  bool get isHighVerbosity =>
      (super.noSuchMethod(
            Invocation.getter(#isHighVerbosity),
            returnValue: false,
          )
          as bool);

  @override
  bool get hapticsEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#hapticsEnabled),
            returnValue: false,
          )
          as bool);

  @override
  double get fontSizeFactor =>
      (super.noSuchMethod(Invocation.getter(#fontSizeFactor), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setHandedness({required bool? isLeft}) => super.noSuchMethod(
    Invocation.method(#setHandedness, [], {#isLeft: isLeft}),
    returnValueForMissingStub: null,
  );

  @override
  void setHighContrast(bool? value) => super.noSuchMethod(
    Invocation.method(#setHighContrast, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setHighVerbosity(bool? value) => super.noSuchMethod(
    Invocation.method(#setHighVerbosity, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setHaptics(bool? value) => super.noSuchMethod(
    Invocation.method(#setHaptics, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setFontSize(double? value) => super.noSuchMethod(
    Invocation.method(#setFontSize, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> login(
    String? username,
    String? password, {
    _i4.VoidCallback? onSuccess,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #login,
              [username, password],
              {#onSuccess: onSuccess},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.RegisterResponse?> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue: _i3.Future<_i5.RegisterResponse?>.value(),
          )
          as _i3.Future<_i5.RegisterResponse?>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void resetError() => super.noSuchMethod(
    Invocation.method(#resetError, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateHouseholdCode(String? code) => super.noSuchMethod(
    Invocation.method(#updateHouseholdCode, [code]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
