// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/providers/notification/notification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:frontend/models/auth/login_request.dart' as _i11;
import 'package:frontend/models/auth/login_response.dart' as _i3;
import 'package:frontend/models/auth/register_response.dart' as _i4;
import 'package:frontend/models/notification_model.dart' as _i9;
import 'package:frontend/models/user_profile.dart' as _i5;
import 'package:frontend/services/auth/auth_service.dart' as _i10;
import 'package:frontend/services/notification/notification_service.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterResponse_2 extends _i1.SmartFake
    implements _i4.RegisterResponse {
  _FakeRegisterResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_3 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i8.Future<List<_i9.NotificationModel>> fetchNotifications(
    String? jwtToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchNotifications, [jwtToken]),
            returnValue: _i8.Future<List<_i9.NotificationModel>>.value(
              <_i9.NotificationModel>[],
            ),
          )
          as _i8.Future<List<_i9.NotificationModel>>);

  @override
  _i8.Future<void> markAsRead(int? notificationId, String? jwtToken) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId, jwtToken]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteNotification(int? notificationId, String? jwtToken) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId, jwtToken]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> markAllAsRead(String? jwtToken) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [jwtToken]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getUnreadCount(String? jwtToken) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [jwtToken]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.FlutterSecureStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFlutterSecureStorage_0(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i2.FlutterSecureStorage);

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getStoredToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i11.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i4.RegisterResponse> register(
    String? username,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, email, password]),
            returnValue: _i8.Future<_i4.RegisterResponse>.value(
              _FakeRegisterResponse_2(
                this,
                Invocation.method(#register, [username, email, password]),
              ),
            ),
          )
          as _i8.Future<_i4.RegisterResponse>);

  @override
  _i8.Future<void> updateDeviceToken(
    String? token, {
    String? deviceName = 'unknown',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateDeviceToken,
              [token],
              {#deviceName: deviceName},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeDeviceToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#removeDeviceToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.UserProfile> fetchProfile(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [token]),
            returnValue: _i8.Future<_i5.UserProfile>.value(
              _FakeUserProfile_3(
                this,
                Invocation.method(#fetchProfile, [token]),
              ),
            ),
          )
          as _i8.Future<_i5.UserProfile>);
}
